apiVersion: 1

datasources:
  - name: Network Mapper Prometheus
    uid: network-mapper-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
